ALTER TABLE count_entries
  ADD COLUMN IF NOT EXISTS is_weight_count BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE reconciliation_items
  ADD COLUMN IF NOT EXISTS is_weight_count BOOLEAN NOT NULL DEFAULT FALSE;
